travis:
  secure:
    BINSTAR_TOKEN: KcKwCbIM6QxALIsABBydTJlq1uGZALHRWXKlnwJ6ESlQPwtqs3EJqcpTJzCaTrCOGe3vwoYXRcWN4EeMH76/tkDhn7gzH6wXnfHUbOHhTkWNIf91OnozDfgkcz1kTMUf6jHQ7J7U/BG5QTOTdamDZR6QwE2QvgVr2fhge6xsL6sqIe9AFaSyOmPO8AqfBj0YVHuWD7dR1/JbSa21b0uoy6HR/nRhNSFsBgoyQOin2NXSKCf/TgczezTaDtvc3W5yHb+xGZAlk998JtQo7KBQiD7XZ7w/2F8zw1ybeGqcOClA1cklAeUZg03V9LEaFAX5y1POh+h8c9wvSVIsYg758IG38LSPkhP1TcJQOYOkrM2BJB8BJcf7UFNXUSuEWGerhdxlHOXJ0eD37gx0Fwh5L0+0+9vc+RiXdgtDz+7yzkEnP9mvejHSXbRNPkthVz5KbttYAlSxRJgVjOXIdI2XvtDZpT/0+YVLuKUEpgomuXyARmqPlUHPRJ5kBXhBe5hcOLQ1jrwHkpEDrBSjanEwu/nYnEt33kDt359UYmwQe1Jja0B8HdgPs3r5WTxp5ZOnNQFOfGIhf0QloEspQwyBIG3xWTiCsWfoqj0RR6XS7apWwAyVFrDsP/xtsSHUZl5Ea4gRF09iejWgCc77Msv0l4meQqEpWc71i/5WR3rQYZw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
